[package]
name = "platform_library_macro"
version = "0.0.0"
edition = "2024"

[lib]
proc-macro = true


[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["full"] }
